package com.ohmyguide.app.ui.theme.strings

import com.ohmyguide.app.ui.theme.AppStrings

object EnStrings : AppStrings {
    override val appName = "Oh My Guide"
    override val back = "Back"
    override val send = "Send"
    override val remove = "Remove"
    override val stop = "Stop"
    override val skip = "Skip"
    override val restore = "Restore"
    override val map = "Map"
    override val next = "Next"

    override val navHome = "Home"
    override val navExplore = "Explore"
    override val navPhrases = "Phrases"

    override val splashSubtitle = "Your Special Korea Tour Guide Service"

    override val welcomeGreeting = "Annyeong!"
    override val welcomeIntro = "I'm your Korea guide"
    override val welcomeDesc = "Find amazing places,\nnavigate like a local,\nand get personalized guides."
    override val signInGoogle = "Sign in with Google"
    override val signInHint = "One-tap sign in to get your personalized guide"
    override val loginSuccess = "You have successfully logged in."

    override val onboardLangPrompt = "Find the Best Spots Near You!\nTo give you the best experience,\nwhat language do you prefer?"
    override val onboardGenderPrompt = "Great! And what is your gender?"
    override val onboardAgePrompt = "Nice! How old are you?"
    override val onboardCountryPrompt = "Where are you from?"
    override val onboardCompanionPrompt = "Awesome! Who are you traveling with?"
    override val onboardGpsPrompt = "Perfect! Lastly, please allow location access so we can explore together."
    override val allowLocation = "Allow Location Access"
    override val enterAge = "Enter your age"
    override val yearsOld = " years old"
    override val ageConfirm = "I'm %d years old"
    override val selectCountry = "Select your country"
    override val female = "Female"
    override val male = "Male"
    override val friends = "Friends"
    override val family = "Family"
    override val solo = "Solo"
    override val partner = "Partner"

    override val detectingLocation = "Detecting your location..."
    override val yourLocation = "Your Location"
    override val categoryGreeting = "Hello! I'm Kkaebi.\nLet me find the perfect spots near you!"
    override val categoryPrompt = "Just tell me what you're into"
    override val categoryDone = "Great choices! Let me find the best spots for you."
    override val chooseInterests = "Choose what interests you!"
    override val addMoreOrSend = "Great pick! Add more or send"
    override val categoriesSelected = "categories selected"

    override val categoryNames = mapOf(
        "attraction" to "Attraction", "culture" to "Culture", "festival" to "Festival",
        "course" to "Course", "leports" to "Leports", "cafe" to "Cafes",
        "shopping" to "Shopping", "food" to "Food",
    )
    override val categorySubs = mapOf(
        "attraction" to "Landmarks & nature", "culture" to "Museums & history",
        "festival" to "Events & performances", "course" to "Travel routes",
        "leports" to "Leisure & sports", "cafe" to "Coffee & bakeries",
        "shopping" to "Markets & malls", "food" to "Dining & street eats",
    )

    override val findingSpots = "Finding amazing spots..."
    override val scanningNearby = "Scanning nearby places\nbased on your interests"

    override val curatingSpots = "Curating spots..."
    override val curatingDone = "Your guide is ready"
    override val reset = "Reset"
    override val near = "Near"
    override val spots = "spots"
    override val yourArea = "your area"
    override val backToList = "Back to list"
    override val findOtherPlaces = "Find other places"
    override val goHere = "Go here"

    override val hotThisWeek = "Hot This Week"
    override val courses = "Courses"
    override val allCourses = "All Courses"
    override val kCulture = "K-Culture"
    override val explore = "Explore"
    override val trending = "TRENDING"
    override val diveIntoKCulture = "Dive into\nK-Culture"
    override val curatedCourses = "Curated courses by locals & K-fans"
    override val noCoursesFound = "No courses found"
    override val tryDifferentRegion = "Try a different region or category"
    override val exploreThisCourse = "Explore This Course"
    override val seeAllCourses = "See All Courses"
    override val swipeToDiscover = "Swipe to discover more"
    override val courseRoute = "COURSE ROUTE"
    override val startCourseNavi = "Start Course Navigation"
    override val courseProgress = "COURSE PROGRESS"
    override val rightHere = "Right here"

    override val destination = "Destination"
    override val tapToSeeRoutes = "Tap below to see available routes"
    override val viewTransitRoutes = "View Transit Routes"
    override val startNavigation = "Start Navigation"
    override val walk = "Walk"
    override val enjoyScenery = "Enjoy the scenery"
    override val transit = "Transit"
    override val busAndSubway = "Bus & Subway"
    override val taxi = "Taxi"
    override val taxiCar = "Taxi / Car"
    override val transfer = "Transfer"
    override val subway = "Subway"
    override val direct = "Direct"
    override val stopsUnit = "stops"

    override val walkingTo = "Walking to"
    override val transitTo = "Transit to"
    override val drivingTo = "Driving to"
    override val yesShowMe = "Yes, show me!"
    override val iveArrived = "I've Arrived!"
    override val listen = "Listen"
    override val photo = "Photo"
    override val prices = "Prices"

    override val storyLabel = "Story"
    override val loading = "Loading\u2026"
    override val nowPlaying = "Now playing\u2026"
    override val paused = "Paused"
    override val backToGuide = "Back to Guide"
    override val listenToGuide = "Listen to Guide"

    override val koreanPhrasesTitle = "\uD55C\uAD6D\uC5B4 \uAD6C\uBB38"
    override val koreanPhrasesSubtitle = "Korean Phrases for Travelers"
    override val saved = "saved"
    override val bookmarkHint = "Tap the bookmark to save phrases for quick access offline!"
    override val phrasesUnit = "phrases"

    override val myPage = "My Page"
    override val visitHistory = "Visit History"
    override val placesVisitedDesc = "Places you've been"
    override val bookmarks = "Bookmarks"
    override val savedPlacesDesc = "Saved places & phrases"
    override val storyArchive = "Story Archive"
    override val storiesListenedDesc = "Stories you've listened"
    override val language = "Language"
    override val notifications = "Notifications"
    override val on = "On"
    override val theme = "Theme"
    override val light = "Light"
    override val traveler = "Traveler"
    override val food = "Food"
    override val culture = "Culture"
    override val signOut = "Sign Out"
    override val ageUnit = " yrs"
    override val pickRecommendTitle = "Popular with Travelers Like You"
    override val pickRecommendDesc = "Based on big data from similar travelers"
    override val pickRecommendEmpty = "No recommendations available yet"
    override val editProfile = "Edit Profile"
    override val nationality = "Nationality"
    override val age = "Age"
    override val gender = "Gender"
    override val save = "Save"
    override val profileFieldsRequired = "Please fill in all fields"
    override val bookmarkEmpty = "No saved phrases yet. Tap to browse!"
    override val viewAllPhrases = "View All Phrases"

    // ── Chat / Recommend ──
    override val picksForYou = "Picks for You"
    override val newPicksForYou = "New Picks for You"
    override val noPlacesFound = "No places found"
    override val sorryNoPlaces = "Sorry, no places matched your request"
    override val freshPicks = "Fresh Picks"
    override val mainFocusQuestion = "What's your main focus today?"
    override val vibeQuestion = "What vibe are you going for?"
    override val optionFood = "Food"
    override val optionPhoto = "Photo Spots"
    override val optionShopping = "Shopping"
    override val optionActive = "Active"
    override val optionCalm = "Calm"
    override val optionNightlife = "Nightlife"
    override val showMore = "Show More"
    override val moreSpots = "More Spots"

    // ── Navi Chat ──
    override val guideToPlace = "Guide to this place"
    override val storyAboutPlace = "I have a story about %s!"
    override val usefulPhrases = "Useful phrases nearby"
    override val arrivedAt = "Arrived at"
    override val naviCourseSpotProgress = "\uD83D\uDCCD %s — Spot %d/%d"
    override val naviTransferAhead = "\uD83D\uDD04 %d transfer(s) ahead. I'll guide you when you're close!"
    override val naviFollowTransit = "\uD83D\uDEB6 Follow the transit route! About %d min."
    override val naviDriveTime = "\uD83D\uDE97 Estimated drive time: about %d min. Follow the route on the map!"
    override val naviWalkTime = "\uD83D\uDEB6 Estimated walk time: about %d min. Enjoy the walk!"
    override val naviArrivalPrompt = "\uD83D\uDCCD You're close to %s! Have you arrived?"
    override val naviNearbySpot = "\uD83D\uDCCD There's a place called %s nearby! Want to hear about it?"

    // ── Weather ──
    override val weatherIntro = "Before we start, let me check the weather for you!"
    override val weatherClear = "Clear sky"
    override val weatherMainlyClear = "Mainly clear"
    override val weatherPartlyCloudy = "Partly cloudy"
    override val weatherOvercast = "Overcast"
    override val weatherFoggy = "Foggy"
    override val weatherDrizzle = "Drizzle"
    override val weatherRain = "Rain"
    override val weatherFreezingRain = "Freezing rain"
    override val weatherSnow = "Snow"
    override val weatherSnowGrains = "Snow grains"
    override val weatherRainShowers = "Rain showers"
    override val weatherSnowShowers = "Snow showers"
    override val weatherThunderstorm = "Thunderstorm"
    override val weatherThunderstormHail = "Thunderstorm with hail"
    override val weatherUnknown = "Unknown"
    override val weatherTipHot = "It's very hot! Stay hydrated and find shade when possible."
    override val weatherTipWarm = "It's warm outside. Light clothing recommended."
    override val weatherTipFeelsCold = "Feels colder than it looks (%s). Layer up!"
    override val weatherTipMild = "Mild weather. A light jacket might be nice."
    override val weatherTipCold = "It's cold! Bundle up warmly."
    override val weatherTipStrongWind = "\uD83C\uDF2A\uFE0F Very strong wind (%s m/s). Be careful outdoors!"
    override val weatherTipWindy = "\uD83D\uDCA8 Windy today (%s m/s). Hold onto your hat!"
    override val weatherTipRaining = "\u2602\uFE0F Bring an umbrella \u2014 it's raining!"
    override val weatherTipSnowing = "\uD83E\uDDE4 Snow expected \u2014 dress warmly and watch your step."
    override val weatherTipThunderstorm = "\u26A1 Thunderstorm alert! Consider staying indoors."
    override val weatherTipRainChance = "\u2602\uFE0F %s%% chance of rain \u2014 umbrella recommended."
    override val weatherTipDark = "\uD83C\uDF19 It's getting dark. Stay on well-lit paths!"
    override val weatherTipGreat = "Great weather for exploring!"
    override val weatherTipClearNight = "Clear night. Enjoy the night views!"

    override val locating = "Locating..."
    override val mapView = "Map View"
    override val explorePlaces = "Explore places around you"
    override val storyPromptHint = "See the 🎧 button at the top? Tap it anytime to listen while you walk!"

    override val hours = "Hours"
    override val fee = "Fee"
    override val distance = "Distance"
    override val preview = "Preview"
    override val placeNo = "NO"
    override val placeGo = "GO"

    override val transitRoutes = "Transit Routes"
    override val searchingRoutes = "Searching routes..."
    override val noTransitRoutes = "No transit routes found"
    override val tryWalkOrCar = "Try walking or car instead"
    override val filterAll = "All"
    override val busLabel = "Bus"
    override val busSubwayLabel = "Bus+Subway"
    override val minSuffix = "min"
    override val hourSuffix = "h"
    override val minWalkSuffix = "min walk"
    override val etaPrefix = "ETA"
    override val notAvailable = "N/A"
    override val stopsAway = "stops away"
    override val listenToStory = "Listen to Story"
    override val getOffAt = "Get off at"
    override val currentLocation = "Current Location"

    override val endNaviTitle = "End Navigation?"
    override val endNaviMessage = "Are you sure you want to stop navigating?"
    override val confirm = "End"
    override val cancel = "Cancel"
    override val movingToNextCourse = "Moving to the next spot!"

    // ── Rating ──
    override val ratingTitle = "How was your guide?"
    override val ratingSubtitle = "Rate your experience at"
    override val ratingSubmit = "Submit"

    override val noRecommendations = "No recommendations yet"
    override val noRecommendationsDesc = "Tell us your interests to get personalized spots"
    override val noSavedPhrases = "No saved phrases"
    override val noSavedPhrasesDesc = "Bookmark phrases to access them offline"
}