package com.ohmyguide.app.ui.theme.strings

import com.ohmyguide.app.ui.theme.AppStrings

object JaStrings : AppStrings {
    override val appName = "Oh My Guide"
    override val back = "戻る"
    override val send = "送信"
    override val remove = "削除"
    override val stop = "停止"
    override val skip = "スキップ"
    override val restore = "復元"
    override val map = "地図"
    override val next = "次へ"

    override val navHome = "ホーム"
    override val navExplore = "探索"
    override val navPhrases = "フレーズ"

    override val splashSubtitle = "あなただけの特別な韓国旅行ガイド"

    override val welcomeGreeting = "アンニョン!"
    override val welcomeIntro = "韓国ガイドです"
    override val welcomeDesc = "素敵な場所を見つけ、\n地元の人のように移動し、\nパーソナルガイドを手に入れよう。"
    override val signInGoogle = "Googleでサインイン"
    override val signInHint = "ワンタップでログインしてガイドを手に入れよう"
    override val loginSuccess = "ログインに成功しました。"

    override val onboardLangPrompt = "近くのベストスポットを見つけよう！\n最高の体験のために、\nお好みの言語を選んでください。"
    override val onboardGenderPrompt = "いいですね！性別を教えてください。"
    override val onboardAgePrompt = "いいですね！おいくつですか？"
    override val onboardCountryPrompt = "どこの国から来ましたか？"
    override val onboardCompanionPrompt = "素晴らしい！誰と旅行していますか？"
    override val onboardGpsPrompt = "完璧！最後に、一緒に探検するために\n位置情報のアクセスを許可してください。"
    override val allowLocation = "位置情報のアクセスを許可"
    override val enterAge = "年齢を入力"
    override val yearsOld = "歳"
    override val ageConfirm = "I'm %d years old"
    override val selectCountry = "Select your country"
    override val female = "女性"
    override val male = "男性"
    override val friends = "友達"
    override val family = "家族"
    override val solo = "一人"
    override val partner = "Partner"

    override val detectingLocation = "位置を検出中..."
    override val yourLocation = "現在地"
    override val categoryGreeting = "こんにちは！ケビです。\n近くの最高のスポットをお探しします！"
    override val categoryPrompt = "興味のあることを教えてください"
    override val categoryDone = "素晴らしい選択です！最高のスポットをお探しします。"
    override val chooseInterests = "興味のあるものを選んでください！"
    override val addMoreOrSend = "いい選択！追加するか送信してください"
    override val categoriesSelected = "カテゴリー選択中"

    override val categoryNames = mapOf(
        "attraction" to "Attraction", "culture" to "Culture", "festival" to "Festival",
        "course" to "Course", "leports" to "Leports", "cafe" to "Cafes",
        "shopping" to "Shopping", "food" to "Food",
    )
    override val categorySubs = mapOf(
        "attraction" to "Landmarks & nature", "culture" to "Museums & history",
        "festival" to "Events & performances", "course" to "Travel routes",
        "leports" to "Leisure & sports", "cafe" to "Coffee & bakeries",
        "shopping" to "Markets & malls", "food" to "Dining & street eats",
    )

    override val findingSpots = "素敵なスポットを探しています..."
    override val scanningNearby = "あなたの興味に基づいて\n近くの場所をスキャン中"

    override val curatingSpots = "スポットをキュレーション中..."
    override val curatingDone = "ガイドの準備完了"
    override val reset = "リセット"
    override val near = "付近"
    override val spots = "スポット"
    override val yourArea = "このエリア"
    override val backToList = "リストに戻る"
    override val findOtherPlaces = "他の場所を探す"
    override val goHere = "ここへ行く"

    override val hotThisWeek = "今週の注目"
    override val courses = "コース"
    override val allCourses = "すべてのコース"
    override val kCulture = "K-Culture"
    override val explore = "探索"
    override val trending = "トレンド"
    override val diveIntoKCulture = "K-Cultureに\n飛び込もう"
    override val curatedCourses = "地元の人とK-ファンが厳選したコース"
    override val noCoursesFound = "コースが見つかりません"
    override val tryDifferentRegion = "別の地域やカテゴリーを試してみてください"
    override val exploreThisCourse = "コースを探索"
    override val seeAllCourses = "すべてのコースを見る"
    override val swipeToDiscover = "スワイプしてもっと見る"
    override val courseRoute = "コースルート"
    override val startCourseNavi = "コースナビを開始"
    override val courseProgress = "コース進捗"
    override val rightHere = "すぐここ"

    override val destination = "目的地"
    override val tapToSeeRoutes = "下をタップして利用可能なルートを表示"
    override val viewTransitRoutes = "交通ルートを表示"
    override val startNavigation = "ナビを開始"
    override val walk = "徒歩"
    override val enjoyScenery = "景色を楽しむ"
    override val transit = "公共交通"
    override val busAndSubway = "バス＆地下鉄"
    override val taxi = "タクシー"
    override val taxiCar = "タクシー / 車"
    override val transfer = "乗り換え"
    override val subway = "地下鉄"
    override val direct = "直行"
    override val stopsUnit = "駅"

    override val walkingTo = "徒歩で移動中"
    override val transitTo = "交通機関で移動中"
    override val drivingTo = "車で移動中"
    override val yesShowMe = "はい、見せて！"
    override val iveArrived = "到着しました！"
    override val listen = "聴く"
    override val photo = "写真"
    override val prices = "料金"

    override val storyLabel = "ストーリー"
    override val loading = "読み込み中\u2026"
    override val nowPlaying = "再生中\u2026"
    override val paused = "一時停止"
    override val backToGuide = "ガイドに戻る"
    override val listenToGuide = "ガイドを聞く"

    override val koreanPhrasesTitle = "韓国語フレーズ"
    override val koreanPhrasesSubtitle = "旅行者のための韓国語フレーズ"
    override val saved = "保存済み"
    override val bookmarkHint = "ブックマークをタップしてオフラインで素早くアクセス！"
    override val phrasesUnit = "フレーズ"

    override val myPage = "マイページ"
    override val visitHistory = "訪問履歴"
    override val placesVisitedDesc = "訪れた場所"
    override val bookmarks = "ブックマーク"
    override val savedPlacesDesc = "保存した場所とフレーズ"
    override val storyArchive = "ストーリーアーカイブ"
    override val storiesListenedDesc = "聞いたストーリー"
    override val language = "言語"
    override val notifications = "通知"
    override val on = "オン"
    override val theme = "テーマ"
    override val light = "ライト"
    override val traveler = "旅行者"
    override val food = "食べ物"
    override val culture = "文化"
    override val signOut = "ログアウト"
    override val ageUnit = "歳"
    override val pickRecommendTitle = "似た旅行者に人気のスポット"
    override val pickRecommendDesc = "ビッグデータに基づくおすすめ"
    override val pickRecommendEmpty = "まだおすすめデータがありません"
    override val editProfile = "プロフィール編集"
    override val nationality = "国籍"
    override val age = "年齢"
    override val gender = "性別"
    override val save = "保存"
    override val profileFieldsRequired = "すべての項目を入力してください"
    override val bookmarkEmpty = "保存されたフレーズはありません"
    override val viewAllPhrases = "すべてのフレーズを見る"

    // ── Chat / Recommend ──
    override val picksForYou = "あなたへのおすすめ"
    override val newPicksForYou = "新しいおすすめ"
    override val noPlacesFound = "場所が見つかりません"
    override val sorryNoPlaces = "ご要望に合う場所が見つかりませんでした"
    override val freshPicks = "新着おすすめ"
    override val mainFocusQuestion = "今日は何をしたいですか？"
    override val vibeQuestion = "どんな雰囲気がお好みですか？"
    override val optionFood = "グルメ"
    override val optionPhoto = "フォトスポット"
    override val optionShopping = "ショッピング"
    override val optionActive = "アクティブ"
    override val optionCalm = "癒し"
    override val optionNightlife = "ナイトライフ"
    override val showMore = "もっと見る"
    override val moreSpots = "もっとスポット"

    // ── Navi Chat ──
    override val guideToPlace = "この場所のガイド"
    override val storyAboutPlace = "%sについてのお話があります！"
    override val usefulPhrases = "近くで使えるフレーズ"
    override val arrivedAt = "到着:"
    override val naviCourseSpotProgress = "\uD83D\uDCCD %s — スポット %d/%d"
    override val naviTransferAhead = "\uD83D\uDD04 乗り換え%d回あり。近づいたらご案内します！"
    override val naviFollowTransit = "\uD83D\uDE8C 交通ルートに沿って進んでください！約%d分です。"
    override val naviDriveTime = "\uD83D\uDE97 予想運転時間：約%d分。地図のルートに沿ってください！"
    override val naviWalkTime = "\uD83D\uDEB6 予想徒歩時間：約%d分。散歩を楽しんでください！"
    override val naviArrivalPrompt = "\uD83D\uDCCD %sの近くです！到着しましたか？"
    override val naviNearbySpot = "\uD83D\uDCCD 近くに%sがあります！聞いてみますか？"

    // ── Weather ──
    override val weatherIntro = "出発前にお天気をチェックしますね！"
    override val weatherClear = "快晴"
    override val weatherMainlyClear = "おおむね晴れ"
    override val weatherPartlyCloudy = "一部曇り"
    override val weatherOvercast = "曇り"
    override val weatherFoggy = "霧"
    override val weatherDrizzle = "霧雨"
    override val weatherRain = "雨"
    override val weatherFreezingRain = "凍雨"
    override val weatherSnow = "雪"
    override val weatherSnowGrains = "霰"
    override val weatherRainShowers = "にわか雨"
    override val weatherSnowShowers = "吹雪"
    override val weatherThunderstorm = "雷雨"
    override val weatherThunderstormHail = "雹を伴う雷雨"
    override val weatherUnknown = "不明"
    override val weatherTipHot = "とても暑いです！水分補給と日陰を見つけてください。"
    override val weatherTipWarm = "暖かい天気です。軽い服装がおすすめです。"
    override val weatherTipFeelsCold = "体感温度が低めです（%s）。重ね着をしましょう！"
    override val weatherTipMild = "穏やかな天気です。軽いジャケットがあると良いかも。"
    override val weatherTipCold = "寒いです！暖かくしてください。"
    override val weatherTipStrongWind = "\uD83C\uDF2A\uFE0F 非常に強い風（%s m/s）。外出時はご注意ください！"
    override val weatherTipWindy = "\uD83D\uDCA8 風が強いです（%s m/s）。帽子にご注意を！"
    override val weatherTipRaining = "\u2602\uFE0F 傘を持っていきましょう \u2014 雨が降っています！"
    override val weatherTipSnowing = "\uD83E\uDDE4 雪の予報です \u2014 暖かくして足元にお気をつけて。"
    override val weatherTipThunderstorm = "\u26A1 雷雨警報！室内に留まることをおすすめします。"
    override val weatherTipRainChance = "\u2602\uFE0F 降水確率%s%% \u2014 傘をおすすめします。"
    override val weatherTipDark = "\uD83C\uDF19 暗くなってきました。明るい道を歩いてください！"
    override val weatherTipGreat = "探索日和です！"
    override val weatherTipClearNight = "澄んだ夜です。夜景を楽しんでください！"

    override val locating = "位置を確認中..."
    override val mapView = "地図ビュー"
    override val explorePlaces = "周辺のスポットを探索"
    override val storyPromptHint = "上部の🎧ボタンが見えますか？歩きながらいつでもタップして聴けます！"

    override val hours = "営業時間"
    override val fee = "料金"
    override val distance = "距離"
    override val preview = "プレビュー"
    override val placeNo = "いいえ"
    override val placeGo = "行く"

    override val transitRoutes = "乗り換え案内"
    override val searchingRoutes = "ルート検索中..."
    override val noTransitRoutes = "交通ルートが見つかりません"
    override val tryWalkOrCar = "徒歩や車を試してみてください"
    override val filterAll = "すべて"
    override val busLabel = "バス"
    override val busSubwayLabel = "バス+地下鉄"
    override val minSuffix = "分"
    override val hourSuffix = "時間"
    override val minWalkSuffix = "分徒歩"
    override val etaPrefix = "到着予定"
    override val notAvailable = "利用不可"
    override val stopsAway = "駅前"
    override val listenToStory = "ストーリーを聴く"
    override val getOffAt = "下車駅:"
    override val currentLocation = "現在地"

    override val endNaviTitle = "ナビを終了しますか？"
    override val endNaviMessage = "案内を中断して前の画面に戻ります。"
    override val confirm = "終了"
    override val cancel = "キャンセル"
    override val movingToNextCourse = "次のスポットに移動します！"

    // ── Rating ──
    override val ratingTitle = "ガイドはいかがでしたか？"
    override val ratingSubtitle = "体験を評価してください"
    override val ratingSubmit = "送信"

    override val noRecommendations = "おすすめスポットがまだありません"
    override val noRecommendationsDesc = "興味を教えてくれたらぴったりの場所を探します"
    override val noSavedPhrases = "保存したフレーズがありません"
    override val noSavedPhrasesDesc = "ブックマークしてオフラインでも確認しましょう"
}