package com.ohmyguide.app.ui.theme.strings

import com.ohmyguide.app.ui.theme.AppStrings

object ZhCnStrings : AppStrings {
    override val appName = "Oh My Guide"
    override val back = "返回"
    override val send = "发送"
    override val remove = "移除"
    override val stop = "停止"
    override val skip = "跳过"
    override val restore = "恢复"
    override val map = "地图"
    override val next = "下一步"

    override val navHome = "首页"
    override val navExplore = "探索"
    override val navPhrases = "用语"

    override val splashSubtitle = "您的专属韩国旅游导览服务"

    override val welcomeGreeting = "安妞！"
    override val welcomeIntro = "我是你的韩国导游"
    override val welcomeDesc = "发现精彩景点，\n像当地人一样导航，\n获得个性化导览。"
    override val signInGoogle = "使用 Google 登录"
    override val signInHint = "一键登录，获取您的专属导览"
    override val loginSuccess = "登录成功。"

    override val onboardLangPrompt = "寻找您附近的最佳景点！\n为了提供最佳体验，\n请选择您偏好的语言。"
    override val onboardGenderPrompt = "太好了！请问您的性别是？"
    override val onboardAgePrompt = "很好！请问您几岁？"
    override val onboardCountryPrompt = "您来自哪个国家？"
    override val onboardCompanionPrompt = "太棒了！您和谁一起旅行？"
    override val onboardGpsPrompt = "太好了！最后，请允许位置访问，\n让我们一起探索。"
    override val allowLocation = "允许位置访问"
    override val enterAge = "请输入年龄"
    override val yearsOld = "岁"
    override val ageConfirm = "I'm %d years old"
    override val selectCountry = "Select your country"
    override val female = "女性"
    override val male = "男性"
    override val friends = "朋友"
    override val family = "家人"
    override val solo = "独自"
    override val partner = "Partner"

    override val detectingLocation = "正在检测您的位置..."
    override val yourLocation = "您的位置"
    override val categoryGreeting = "您好！我是 Kkaebi。\n让我为您找到附近最棒的景点！"
    override val categoryPrompt = "告诉我你感兴趣的东西"
    override val categoryDone = "很棒的选择！让我为您找到最佳景点。"
    override val chooseInterests = "选择你感兴趣的！"
    override val addMoreOrSend = "好选择！继续添加或发送"
    override val categoriesSelected = "个类别已选择"

    override val categoryNames = mapOf(
        "attraction" to "Attraction", "culture" to "Culture", "festival" to "Festival",
        "course" to "Course", "leports" to "Leports", "cafe" to "Cafes",
        "shopping" to "Shopping", "food" to "Food",
    )
    override val categorySubs = mapOf(
        "attraction" to "Landmarks & nature", "culture" to "Museums & history",
        "festival" to "Events & performances", "course" to "Travel routes",
        "leports" to "Leisure & sports", "cafe" to "Coffee & bakeries",
        "shopping" to "Markets & malls", "food" to "Dining & street eats",
    )

    override val findingSpots = "正在寻找精彩景点..."
    override val scanningNearby = "根据您的兴趣\n扫描附近的景点"

    override val curatingSpots = "精选景点中..."
    override val curatingDone = "导览已就绪"
    override val reset = "重置"
    override val near = "附近"
    override val spots = "景点"
    override val yourArea = "您的区域"
    override val backToList = "返回列表"
    override val findOtherPlaces = "寻找其他景点"
    override val goHere = "前往这里"

    override val hotThisWeek = "本周热门"
    override val courses = "路线"
    override val allCourses = "所有路线"
    override val kCulture = "K-Culture"
    override val explore = "探索"
    override val trending = "热门"
    override val diveIntoKCulture = "深入体验\nK-Culture"
    override val curatedCourses = "由本地人和K-粉丝精选的路线"
    override val noCoursesFound = "找不到路线"
    override val tryDifferentRegion = "试试不同的地区或类别"
    override val exploreThisCourse = "探索此路线"
    override val seeAllCourses = "查看所有路线"
    override val swipeToDiscover = "滑动发现更多"
    override val courseRoute = "路线规划"
    override val startCourseNavi = "开始路线导航"
    override val courseProgress = "路线进度"
    override val rightHere = "就在这里"

    override val destination = "目的地"
    override val tapToSeeRoutes = "点击下方查看可用路线"
    override val viewTransitRoutes = "查看交通路线"
    override val startNavigation = "开始导航"
    override val walk = "步行"
    override val enjoyScenery = "享受风景"
    override val transit = "公共交通"
    override val busAndSubway = "公交和地铁"
    override val taxi = "出租车"
    override val taxiCar = "出租车 / 汽车"
    override val transfer = "换乘"
    override val subway = "地铁"
    override val direct = "直达"
    override val stopsUnit = "站"

    override val walkingTo = "步行前往"
    override val transitTo = "搭乘公共交通前往"
    override val drivingTo = "驾车前往"
    override val yesShowMe = "好的，带我看看！"
    override val iveArrived = "我到了！"
    override val listen = "收听"
    override val photo = "照片"
    override val prices = "价格"

    override val storyLabel = "故事"
    override val loading = "加载中\u2026"
    override val nowPlaying = "播放中\u2026"
    override val paused = "已暂停"
    override val backToGuide = "返回导览"
    override val listenToGuide = "收听导览"

    override val koreanPhrasesTitle = "韩语短语"
    override val koreanPhrasesSubtitle = "旅客韩语常用语"
    override val saved = "已保存"
    override val bookmarkHint = "点击书签保存用语，离线也能快速查看！"
    override val phrasesUnit = "个短语"

    override val myPage = "我的页面"
    override val visitHistory = "参观记录"
    override val placesVisitedDesc = "您去过的地方"
    override val bookmarks = "书签"
    override val savedPlacesDesc = "已保存的地点和用语"
    override val storyArchive = "故事档案"
    override val storiesListenedDesc = "您听过的故事"
    override val language = "语言"
    override val notifications = "通知"
    override val on = "开启"
    override val theme = "主题"
    override val light = "浅色"
    override val traveler = "旅客"
    override val food = "美食"
    override val culture = "文化"
    override val signOut = "退出登录"
    override val ageUnit = "岁"
    override val pickRecommendTitle = "相似旅行者的热门地点"
    override val pickRecommendDesc = "基于大数据的个性化推荐"
    override val pickRecommendEmpty = "暂无推荐数据"
    override val editProfile = "编辑资料"
    override val nationality = "国籍"
    override val age = "年龄"
    override val gender = "性别"
    override val save = "保存"
    override val profileFieldsRequired = "请填写所有字段"
    override val bookmarkEmpty = "暂无收藏短语"
    override val viewAllPhrases = "查看全部短语"

    // ── Chat / Recommend ──
    override val picksForYou = "为你推荐"
    override val newPicksForYou = "新推荐"
    override val noPlacesFound = "未找到景点"
    override val sorryNoPlaces = "抱歉，没有找到符合要求的景点"
    override val freshPicks = "最新推荐"
    override val mainFocusQuestion = "今天想做什么？"
    override val vibeQuestion = "想要什么样的氛围？"
    override val optionFood = "美食"
    override val optionPhoto = "拍照景点"
    override val optionShopping = "购物"
    override val optionActive = "活力"
    override val optionCalm = "休闲"
    override val optionNightlife = "夜生活"
    override val showMore = "查看更多"
    override val moreSpots = "更多景点"

    // ── Navi Chat ──
    override val guideToPlace = "这个地方的导览"
    override val storyAboutPlace = "我有一个关于%s的故事！"
    override val usefulPhrases = "附近实用用语"
    override val arrivedAt = "已到达"
    override val naviCourseSpotProgress = "\uD83D\uDCCD %s — 第%d/%d站"
    override val naviTransferAhead = "\uD83D\uDD04 还需换乘%d次，靠近时会为您导航！"
    override val naviFollowTransit = "\uD83D\uDE8C 请沿公交路线前行！大约%d分钟。"
    override val naviDriveTime = "\uD83D\uDE97 预计驾车时间：约%d分钟。请沿地图路线行驶！"
    override val naviWalkTime = "\uD83D\uDEB6 预计步行时间：约%d分钟。祝您散步愉快！"
    override val naviArrivalPrompt = "\uD83D\uDCCD 您已接近%s！到达了吗？"
    override val naviNearbySpot = "\uD83D\uDCCD 附近有一个叫%s的地方！想了解一下吗？"

    // ── Weather ──
    override val weatherIntro = "出发前帮您看看天气！"
    override val weatherClear = "晴朗"
    override val weatherMainlyClear = "大部晴朗"
    override val weatherPartlyCloudy = "局部多云"
    override val weatherOvercast = "阴天"
    override val weatherFoggy = "有雾"
    override val weatherDrizzle = "毛毛雨"
    override val weatherRain = "下雨"
    override val weatherFreezingRain = "冻雨"
    override val weatherSnow = "下雪"
    override val weatherSnowGrains = "雪粒"
    override val weatherRainShowers = "阵雨"
    override val weatherSnowShowers = "暴风雪"
    override val weatherThunderstorm = "雷暴"
    override val weatherThunderstormHail = "雷暴伴冰雹"
    override val weatherUnknown = "未知"
    override val weatherTipHot = "非常炎热！请注意补充水分，尽量待在阴凉处。"
    override val weatherTipWarm = "天气温暖，建议穿着轻便。"
    override val weatherTipFeelsCold = "体感温度较低（%s），建议多穿几层！"
    override val weatherTipMild = "天气温和，带件薄外套不错。"
    override val weatherTipCold = "很冷！请穿暖和些。"
    override val weatherTipStrongWind = "\uD83C\uDF2A\uFE0F 风力很大（%s m/s），外出请注意安全！"
    override val weatherTipWindy = "\uD83D\uDCA8 今天有风（%s m/s），注意帽子别被吹走！"
    override val weatherTipRaining = "\u2602\uFE0F 带把伞吧 \u2014 正在下雨！"
    override val weatherTipSnowing = "\uD83E\uDDE4 预计有雪 \u2014 穿暖和些，注意脚下。"
    override val weatherTipThunderstorm = "\u26A1 雷暴预警！建议留在室内。"
    override val weatherTipRainChance = "\u2602\uFE0F 降雨概率%s%% \u2014 建议带伞。"
    override val weatherTipDark = "\uD83C\uDF19 天色渐暗，请走有路灯的道路！"
    override val weatherTipGreat = "很适合出去逛逛的好天气！"
    override val weatherTipClearNight = "夜空晴朗，享受夜景吧！"

    override val locating = "定位中..."
    override val mapView = "地图视图"
    override val explorePlaces = "探索您周围的景点"
    override val storyPromptHint = "看到顶部的🎧按钮了吗？走路时随时点击收听！"

    override val hours = "营业时间"
    override val fee = "费用"
    override val distance = "距离"
    override val preview = "预览"
    override val placeNo = "否"
    override val placeGo = "前往"

    override val transitRoutes = "公交路线"
    override val searchingRoutes = "正在搜索路线..."
    override val noTransitRoutes = "未找到公共交通路线"
    override val tryWalkOrCar = "可以试试步行或打车"
    override val filterAll = "全部"
    override val busLabel = "公交"
    override val busSubwayLabel = "公交+地铁"
    override val minSuffix = "分钟"
    override val hourSuffix = "小时"
    override val minWalkSuffix = "分钟步行"
    override val etaPrefix = "预计到达"
    override val notAvailable = "不可用"
    override val stopsAway = "站前到达"
    override val listenToStory = "收听故事"
    override val getOffAt = "在此下车:"
    override val currentLocation = "当前位置"

    override val endNaviTitle = "结束导航？"
    override val endNaviMessage = "确定要停止导航吗？"
    override val confirm = "结束"
    override val cancel = "取消"
    override val movingToNextCourse = "前往下一个景点！"

    // ── Rating ──
    override val ratingTitle = "导览体验如何？"
    override val ratingSubtitle = "请评价您的体验"
    override val ratingSubmit = "提交"

    override val noRecommendations = "暂无推荐景点"
    override val noRecommendationsDesc = "告诉我们你的兴趣，为你找到专属景点"
    override val noSavedPhrases = "没有保存的短语"
    override val noSavedPhrasesDesc = "收藏短语以便离线查看"
}