package com.ohmyguide.app.ui.theme.strings

import com.ohmyguide.app.ui.theme.AppStrings

object ZhTwStrings : AppStrings {
    override val appName = "Oh My Guide"
    override val back = "返回"
    override val send = "發送"
    override val remove = "移除"
    override val stop = "停止"
    override val skip = "跳過"
    override val restore = "恢復"
    override val map = "地圖"
    override val next = "下一步"

    override val navHome = "首頁"
    override val navExplore = "探索"
    override val navPhrases = "用語"

    override val splashSubtitle = "您的專屬韓國旅遊導覽服務"

    override val welcomeGreeting = "安妞！"
    override val welcomeIntro = "我是你的韓國導遊"
    override val welcomeDesc = "發現精彩景點，\n像當地人一樣導航，\n獲得個人化導覽。"
    override val signInGoogle = "使用 Google 登入"
    override val signInHint = "一鍵登入，取得您的專屬導覽"
    override val loginSuccess = "登入成功。"

    override val onboardLangPrompt = "尋找您附近的最佳景點！\n為了提供最佳體驗，\n請選擇您偏好的語言。"
    override val onboardGenderPrompt = "太好了！請問您的性別是？"
    override val onboardAgePrompt = "很好！請問您幾歲？"
    override val onboardCountryPrompt = "您來自哪個國家？"
    override val onboardCompanionPrompt = "太棒了！您和誰一起旅行？"
    override val onboardGpsPrompt = "太好了！最後，請允許位置存取，\n讓我們一起探索。"
    override val allowLocation = "允許位置存取"
    override val enterAge = "請輸入年齡"
    override val yearsOld = "歲"
    override val ageConfirm = "I'm %d years old"
    override val selectCountry = "Select your country"
    override val female = "女性"
    override val male = "男性"
    override val friends = "朋友"
    override val family = "家人"
    override val solo = "獨自"
    override val partner = "Partner"

    override val detectingLocation = "正在偵測您的位置..."
    override val yourLocation = "您的位置"
    override val categoryGreeting = "您好！我是 Kkaebi。\n讓我為您找到附近最棒的景點！"
    override val categoryPrompt = "告訴我你感興趣的東西"
    override val categoryDone = "很棒的選擇！讓我為您找到最佳景點。"
    override val chooseInterests = "選擇你感興趣的！"
    override val addMoreOrSend = "好選擇！繼續添加或發送"
    override val categoriesSelected = "個類別已選擇"

    override val categoryNames = mapOf(
        "attraction" to "Attraction", "culture" to "Culture", "festival" to "Festival",
        "course" to "Course", "leports" to "Leports", "cafe" to "Cafes",
        "shopping" to "Shopping", "food" to "Food",
    )
    override val categorySubs = mapOf(
        "attraction" to "Landmarks & nature", "culture" to "Museums & history",
        "festival" to "Events & performances", "course" to "Travel routes",
        "leports" to "Leisure & sports", "cafe" to "Coffee & bakeries",
        "shopping" to "Markets & malls", "food" to "Dining & street eats",
    )

    override val findingSpots = "正在尋找精彩景點..."
    override val scanningNearby = "根據您的興趣\n掃描附近的景點"

    override val curatingSpots = "精選景點中..."
    override val curatingDone = "導覽已就緒"
    override val reset = "重置"
    override val near = "附近"
    override val spots = "景點"
    override val yourArea = "您的區域"
    override val backToList = "返回列表"
    override val findOtherPlaces = "尋找其他景點"
    override val goHere = "前往這裡"

    override val hotThisWeek = "本週熱門"
    override val courses = "路線"
    override val allCourses = "所有路線"
    override val kCulture = "K-Culture"
    override val explore = "探索"
    override val trending = "熱門"
    override val diveIntoKCulture = "深入體驗\nK-Culture"
    override val curatedCourses = "由在地人和K-粉絲精選的路線"
    override val noCoursesFound = "找不到路線"
    override val tryDifferentRegion = "試試不同的地區或類別"
    override val exploreThisCourse = "探索此路線"
    override val seeAllCourses = "查看所有路線"
    override val swipeToDiscover = "滑動發現更多"
    override val courseRoute = "路線規劃"
    override val startCourseNavi = "開始路線導航"
    override val courseProgress = "路線進度"
    override val rightHere = "就在這裡"

    override val destination = "目的地"
    override val tapToSeeRoutes = "點擊下方查看可用路線"
    override val viewTransitRoutes = "查看交通路線"
    override val startNavigation = "開始導航"
    override val walk = "步行"
    override val enjoyScenery = "享受風景"
    override val transit = "大眾運輸"
    override val busAndSubway = "公車和地鐵"
    override val taxi = "計程車"
    override val taxiCar = "計程車 / 汽車"
    override val transfer = "轉乘"
    override val subway = "地鐵"
    override val direct = "直達"
    override val stopsUnit = "站"

    override val walkingTo = "步行前往"
    override val transitTo = "搭乘大眾運輸前往"
    override val drivingTo = "開車前往"
    override val yesShowMe = "好的，帶我看看！"
    override val iveArrived = "我到了！"
    override val listen = "收聽"
    override val photo = "照片"
    override val prices = "價格"

    override val storyLabel = "故事"
    override val loading = "載入中\u2026"
    override val nowPlaying = "播放中\u2026"
    override val paused = "已暫停"
    override val backToGuide = "返回導覽"
    override val listenToGuide = "收聽導覽"

    override val koreanPhrasesTitle = "韓語短語"
    override val koreanPhrasesSubtitle = "旅客韓語常用語"
    override val saved = "已儲存"
    override val bookmarkHint = "點擊書籤保存用語，離線也能快速查看！"
    override val phrasesUnit = "個短語"

    override val myPage = "我的頁面"
    override val visitHistory = "參觀記錄"
    override val placesVisitedDesc = "您去過的地方"
    override val bookmarks = "書籤"
    override val savedPlacesDesc = "已儲存的地點和用語"
    override val storyArchive = "故事檔案"
    override val storiesListenedDesc = "您聽過的故事"
    override val language = "語言"
    override val notifications = "通知"
    override val on = "開啟"
    override val theme = "主題"
    override val light = "淺色"
    override val traveler = "旅客"
    override val food = "美食"
    override val culture = "文化"
    override val signOut = "登出"
    override val ageUnit = "歲"
    override val pickRecommendTitle = "相似旅行者的熱門地點"
    override val pickRecommendDesc = "基於大數據的個性化推薦"
    override val pickRecommendEmpty = "暫無推薦數據"
    override val editProfile = "編輯資料"
    override val nationality = "國籍"
    override val age = "年齡"
    override val gender = "性別"
    override val save = "儲存"
    override val profileFieldsRequired = "請填寫所有欄位"
    override val bookmarkEmpty = "暫無收藏短語"
    override val viewAllPhrases = "查看全部短語"

    // ── Chat / Recommend ──
    override val picksForYou = "為你推薦"
    override val newPicksForYou = "新推薦"
    override val noPlacesFound = "未找到景點"
    override val sorryNoPlaces = "抱歉，沒有找到符合要求的景點"
    override val freshPicks = "最新推薦"
    override val mainFocusQuestion = "今天想做什麼？"
    override val vibeQuestion = "想要什麼樣的氛圍？"
    override val optionFood = "美食"
    override val optionPhoto = "拍照景點"
    override val optionShopping = "購物"
    override val optionActive = "活力"
    override val optionCalm = "休閒"
    override val optionNightlife = "夜生活"
    override val showMore = "查看更多"
    override val moreSpots = "更多景點"

    // ── Navi Chat ──
    override val guideToPlace = "這個地方的導覽"
    override val storyAboutPlace = "我有一個關於%s的故事！"
    override val usefulPhrases = "附近實用用語"
    override val arrivedAt = "已到達"
    override val naviCourseSpotProgress = "\uD83D\uDCCD %s — 第%d/%d站"
    override val naviTransferAhead = "\uD83D\uDD04 還需轉乘%d次，靠近時會為您導航！"
    override val naviFollowTransit = "\uD83D\uDE8C 請沿大眾運輸路線前行！約%d分鐘。"
    override val naviDriveTime = "\uD83D\uDE97 預計駕車時間：約%d分鐘。請沿地圖路線行駛！"
    override val naviWalkTime = "\uD83D\uDEB6 預計步行時間：約%d分鐘。祝您散步愉快！"
    override val naviArrivalPrompt = "\uD83D\uDCCD 您已接近%s！到達了嗎？"
    override val naviNearbySpot = "\uD83D\uDCCD 附近有一個叫%s的地方！想了解一下嗎？"

    // ── Weather ──
    override val weatherIntro = "出發前幫您看看天氣！"
    override val weatherClear = "晴朗"
    override val weatherMainlyClear = "大部晴朗"
    override val weatherPartlyCloudy = "局部多雲"
    override val weatherOvercast = "陰天"
    override val weatherFoggy = "有霧"
    override val weatherDrizzle = "毛毛雨"
    override val weatherRain = "下雨"
    override val weatherFreezingRain = "凍雨"
    override val weatherSnow = "下雪"
    override val weatherSnowGrains = "雪粒"
    override val weatherRainShowers = "陣雨"
    override val weatherSnowShowers = "暴風雪"
    override val weatherThunderstorm = "雷暴"
    override val weatherThunderstormHail = "雷暴伴冰雹"
    override val weatherUnknown = "未知"
    override val weatherTipHot = "非常炎熱！請注意補充水分，盡量待在陰涼處。"
    override val weatherTipWarm = "天氣溫暖，建議穿著輕便。"
    override val weatherTipFeelsCold = "體感溫度較低（%s），建議多穿幾層！"
    override val weatherTipMild = "天氣溫和，帶件薄外套不錯。"
    override val weatherTipCold = "很冷！請穿暖和些。"
    override val weatherTipStrongWind = "\uD83C\uDF2A\uFE0F 風力很大（%s m/s），外出請注意安全！"
    override val weatherTipWindy = "\uD83D\uDCA8 今天有風（%s m/s），注意帽子別被吹走！"
    override val weatherTipRaining = "\u2602\uFE0F 帶把傘吧 \u2014 正在下雨！"
    override val weatherTipSnowing = "\uD83E\uDDE4 預計有雪 \u2014 穿暖和些，注意腳下。"
    override val weatherTipThunderstorm = "\u26A1 雷暴預警！建議留在室內。"
    override val weatherTipRainChance = "\u2602\uFE0F 降雨機率%s%% \u2014 建議帶傘。"
    override val weatherTipDark = "\uD83C\uDF19 天色漸暗，請走有路燈的道路！"
    override val weatherTipGreat = "很適合出去逛逛的好天氣！"
    override val weatherTipClearNight = "夜空晴朗，享受夜景吧！"

    override val locating = "定位中..."
    override val mapView = "地圖檢視"
    override val explorePlaces = "探索您周圍的景點"
    override val storyPromptHint = "看到頂部的🎧按鈕了嗎？走路時隨時點擊收聽！"

    override val hours = "營業時間"
    override val fee = "費用"
    override val distance = "距離"
    override val preview = "預覽"
    override val placeNo = "否"
    override val placeGo = "前往"

    override val transitRoutes = "公車路線"
    override val searchingRoutes = "正在搜尋路線..."
    override val noTransitRoutes = "找不到大眾運輸路線"
    override val tryWalkOrCar = "可以試試步行或搭車"
    override val filterAll = "全部"
    override val busLabel = "公車"
    override val busSubwayLabel = "公車+地鐵"
    override val minSuffix = "分鐘"
    override val hourSuffix = "小時"
    override val minWalkSuffix = "分鐘步行"
    override val etaPrefix = "預計到達"
    override val notAvailable = "不可用"
    override val stopsAway = "站前到達"
    override val listenToStory = "收聽故事"
    override val getOffAt = "在此下車:"
    override val currentLocation = "目前位置"

    override val endNaviTitle = "結束導航？"
    override val endNaviMessage = "確定要停止導航嗎？"
    override val confirm = "結束"
    override val cancel = "取消"
    override val movingToNextCourse = "前往下一個景點！"

    // ── Rating ──
    override val ratingTitle = "導覽體驗如何？"
    override val ratingSubtitle = "請評價您的體驗"
    override val ratingSubmit = "提交"

    override val noRecommendations = "暫無推薦景點"
    override val noRecommendationsDesc = "告訴我們你的興趣，為你找到專屬景點"
    override val noSavedPhrases = "沒有儲存的短語"
    override val noSavedPhrasesDesc = "收藏短語以便離線查看"
}