global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-boot:8080']  ## spring-boot 는 service 이름

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']